import React, { useEffect, useState } from 'react';
import { api } from '../services/api';
import { Interview } from '../types';
import { Award, CheckCircle, AlertTriangle, ArrowRight, BarChart2, Map, PlayCircle } from 'lucide-react';

interface InterviewResultPageProps {
  interviewId: number;
  onNavigate: (tab: string) => void;
}

export const InterviewResultPage: React.FC<InterviewResultPageProps> = ({ interviewId, onNavigate }) => {
  const [interview, setInterview] = useState<Interview | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      try {
        const data = await api.getInterview(interviewId);
        setInterview(data);
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [interviewId]);

  if (loading) return <div style={{ padding: '3rem', textAlign: 'center' }}>Generating Interview Performance Report...</div>;
  if (!interview || !interview.score) {
    return (
      <div className="container" style={{ padding: '3rem', textAlign: 'center' }}>
        <h3>Interview In Progress</h3>
        <p>Complete all questions to view your final readiness evaluation.</p>
      </div>
    );
  }

  const score = interview.score;

  return (
    <div className="container" style={{ padding: '2.5rem 1.5rem', maxWidth: '1000px' }}>
      <div style={{ textAlign: 'center', marginBottom: '2.5rem' }}>
        <span className="badge badge-success" style={{ padding: '0.5rem 1rem', fontSize: '0.85rem', marginBottom: '0.75rem' }}>
          INTERVIEW COMPLETED
        </span>
        <h2>Interview Evaluation & Career Readiness Report</h2>
        <p>Comprehensive multi-category assessment generated by IntervueX AI.</p>
      </div>

      {/* Main Score Hero Card */}
      <div className="card" style={{ background: 'linear-gradient(135deg, #1E3A5F 0%, #1D4ED8 100%)', color: '#FFFFFF', padding: '2.5rem', borderRadius: '16px', marginBottom: '2.5rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1.5rem' }}>
          <div>
            <p style={{ color: '#93C5FD', fontWeight: '700', fontSize: '0.85rem' }}>OVERALL INTERVIEW SCORE</p>
            <h1 style={{ color: '#FFFFFF', fontSize: '4rem', margin: '0.2rem 0', lineHeight: '1' }}>
              {score.overall_score}<span style={{ fontSize: '1.8rem', color: '#94A3B8' }}>/100</span>
            </h1>
            <div style={{ marginTop: '0.75rem' }}>
              <span style={{ background: '#FFFFFF', color: '#1D4ED8', padding: '0.4rem 1rem', borderRadius: '9999px', fontWeight: '800', fontSize: '0.9rem' }}>
                CLASSIFICATION: {score.readiness_category.toUpperCase()}
              </span>
            </div>
          </div>

          {/* Category Scores Grid */}
          <div style={{ background: 'rgba(255,255,255,0.1)', padding: '1.5rem', borderRadius: '12px', minWidth: '280px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.65rem' }}>
              <span>Technical Knowledge:</span>
              <strong>{score.technical_score}/100</strong>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.65rem' }}>
              <span>Problem Solving:</span>
              <strong>{score.problem_solving_score}/100</strong>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.65rem' }}>
              <span>Communication:</span>
              <strong>{score.communication_score}/100</strong>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span>Project Knowledge:</span>
              <strong>{score.project_knowledge_score}/100</strong>
            </div>
          </div>
        </div>
      </div>

      {/* Strengths and Weaknesses */}
      <div className="grid grid-2 gap-6" style={{ marginBottom: '2.5rem' }}>
        <div className="card">
          <h3 style={{ color: '#16A34A', display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
            <CheckCircle size={20} /> STRENGTHS
          </h3>
          <ul style={{ paddingLeft: '1.25rem', fontSize: '0.925rem' }}>
            <li style={{ marginBottom: '0.5rem' }}>Strong technical understanding of core requested framework principles.</li>
            <li style={{ marginBottom: '0.5rem' }}>Clear structured explanation of software architecture and database flow.</li>
            <li style={{ marginBottom: '0.5rem' }}>Good practical examples provided during responses.</li>
          </ul>
        </div>

        <div className="card">
          <h3 style={{ color: '#D97706', display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
            <AlertTriangle size={20} /> AREAS TO IMPROVE
          </h3>
          <ul style={{ paddingLeft: '1.25rem', fontSize: '0.925rem' }}>
            <li style={{ marginBottom: '0.5rem' }}>Elaborate deeper on SQL query optimization and indexing trade-offs.</li>
            <li style={{ marginBottom: '0.5rem' }}>Include microservices scalability and container deployment considerations.</li>
            <li style={{ marginBottom: '0.5rem' }}>Address distributed logging and automated unit testing strategies.</li>
          </ul>
        </div>
      </div>

      {/* Actionable Next Steps Navigation */}
      <div className="card" style={{ textAlign: 'center', background: '#F8FAFC' }}>
        <h3 style={{ marginBottom: '1.25rem' }}>NEXT STEPS FOR CAREER MASTERY</h3>
        <div style={{ display: 'flex', justifyContent: 'center', gap: '1rem', flexWrap: 'wrap' }}>
          <button className="btn btn-primary" onClick={() => onNavigate('roadmap')}>
            <Map size={18} /> View Skill Gaps & 4-Week Roadmap
          </button>
          <button className="btn btn-action" onClick={() => onNavigate('setup')}>
            <PlayCircle size={18} /> Start Another Mock Interview
          </button>
        </div>
      </div>
    </div>
  );
};
