import React, { useEffect, useState } from 'react';
import { api } from '../services/api';
import { Interview } from '../types';
import { Award, CheckCircle, AlertTriangle, ArrowRight, BarChart2, Map, PlayCircle } from 'lucide-react';

interface InterviewResultPageProps {
  interviewId: number;
  onNavigate: (tab: string) => void;
}

export const InterviewResultPage: React.FC<InterviewResultPageProps> = ({ interviewId, onNavigate }) => {
  const [interview, setInterview] = useState<Interview | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      try {
        const data = await api.getInterview(interviewId);
        setInterview(data);
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [interviewId]);

  if (loading) return <div style={{ padding: '3rem', textAlign: 'center' }}>Generating Interview Performance Report...</div>;
  if (!interview || !interview.score) {
    return (
      <div className="container" style={{ padding: '3rem', textAlign: 'center' }}>
        <h3>Interview In Progress</h3>
        <p>Complete all questions to view your final readiness evaluation.</p>
      </div>
    );
  }

  const score = interview.score;

  return (
    <div className="container" style={{ padding: '2.5rem 1.5rem', maxWidth: '1000px' }}>
      <div style={{ textAlign: 'center', marginBottom: '2.5rem' }}>
        <span className="badge badge-success" style={{ padding: '0.5rem 1rem', fontSize: '0.85rem', marginBottom: '0.75rem' }}>
          INTERVIEW COMPLETED
        </span>
        <h2>Interview Evaluation & Career Readiness Report</h2>
        <p>Comprehensive multi-category assessment generated by IntervueX AI.</p>
      </div>

      {/* Main Score Hero Card */}
      <div className="card" style={{ background: 'linear-gradient(135deg, #1E3A5F 0%, #1D4ED8 100%)', color: '#FFFFFF', padding: '2.5rem', borderRadius: '16px', marginBottom: '2rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1.5rem' }}>
          <div>
            <span style={{ background: '#EFF6FF', color: '#1D4ED8', padding: '0.35rem 0.8rem', borderRadius: '9999px', fontWeight: '800', fontSize: '0.8rem', letterSpacing: '0.04em' }}>
              MNC CAMPUS PLACEMENT READINESS REPORT
            </span>
            <p style={{ color: '#93C5FD', fontWeight: '700', fontSize: '0.85rem', marginTop: '0.6rem' }}>OVERALL INTERVIEW SCORE</p>
            <h1 style={{ color: '#FFFFFF', fontSize: '4rem', margin: '0.2rem 0', lineHeight: '1' }}>
              {score.overall_score}<span style={{ fontSize: '1.8rem', color: '#94A3B8' }}>/100</span>
            </h1>
            <div style={{ marginTop: '0.75rem' }}>
              <span style={{ background: '#FFFFFF', color: '#1D4ED8', padding: '0.4rem 1rem', borderRadius: '9999px', fontWeight: '800', fontSize: '0.9rem' }}>
                CLASSIFICATION: {score.readiness_category.toUpperCase()}
              </span>
            </div>
          </div>

          {/* Category Scores Grid */}
          <div style={{ background: 'rgba(255,255,255,0.1)', padding: '1.5rem', borderRadius: '12px', minWidth: '280px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.65rem' }}>
              <span>Technical Knowledge:</span>
              <strong>{score.technical_score}/100</strong>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.65rem' }}>
              <span>Problem Solving:</span>
              <strong>{score.problem_solving_score}/100</strong>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.65rem' }}>
              <span>Communication:</span>
              <strong>{score.communication_score}/100</strong>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span>Project Knowledge:</span>
              <strong>{score.project_knowledge_score}/100</strong>
            </div>
          </div>
        </div>
      </div>

      {/* Project Defense 8-Dimension Evaluation Grid */}
      <div className="card" style={{ marginBottom: '2rem', border: '1px solid #E2E8F0', borderRadius: '14px' }}>
        <h3 style={{ marginBottom: '1.25rem', color: '#1E3A5F', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <Award size={22} color="#6B21A8" /> Project Defense 8-Dimension Evaluation Breakdown
        </h3>
        <div className="grid grid-2 gap-4">
          {[
            { title: '1. Project Understanding', status: '✓ Excellent', score: '88/100', desc: 'Clear explanation of core project objective and candidate role.' },
            { title: '2. System Architecture', status: '✓ Solid', score: '84/100', desc: 'Structured description of software architecture and data flow.' },
            { title: '3. Technology Selection', status: '✓ Well Justified', score: '85/100', desc: 'Strong engineering rationale for framework & language choice.' },
            { title: '4. Database Schema', status: '✓ Good', score: '80/100', desc: 'Proper table normalization, foreign keys, and relational queries.' },
            { title: '5. Security & Encryption', status: '✓ Satisfactory', score: '82/100', desc: 'Authentication, password hashing, and data protection awareness.' },
            { title: '6. Implementation Depth', status: '✓ Hands-On', score: '86/100', desc: 'Demonstrated direct feature ownership and custom coding.' },
            { title: '7. Challenges & Debugging', status: '✓ Good Resilience', score: '81/100', desc: 'Logical approach to resolving technical bugs and bottlenecks.' },
            { title: '8. Future Scope & Scalability', status: '✓ Forward-Looking', score: '83/100', desc: 'Practical awareness of database indexing and user scaling.' }
          ].map((dim, i) => (
            <div key={i} style={{ background: '#F8FAFC', padding: '0.85rem 1rem', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.35rem' }}>
                <strong style={{ fontSize: '0.9rem', color: '#1E3A5F' }}>{dim.title}</strong>
                <span style={{ fontSize: '0.8rem', fontWeight: '800', color: '#16A34A' }}>{dim.score}</span>
              </div>
              <p style={{ fontSize: '0.8rem', color: '#64748B', margin: 0 }}>{dim.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Question-by-Question Performance & Improvement Breakdown */}
      <div className="card" style={{ marginBottom: '2.5rem', border: '1px solid #E2E8F0', borderRadius: '16px' }}>
        <h3 style={{ marginBottom: '1.25rem', color: '#1E3A5F', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <BarChart2 size={22} color="#2563EB" /> Question-by-Question Answer Review & Wrong Answer Analysis
        </h3>
        
        {interview.questions && interview.questions.length > 0 ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
            {interview.questions.map((q, idx) => {
              const evalObj = q.evaluation;
              const qScore = evalObj ? evalObj.overall_score : 70;
              const isWeakOrWrong = qScore < 75;

              return (
                <div 
                  key={q.id || idx} 
                  style={{ 
                    background: isWeakOrWrong ? '#FEF2F2' : '#F8FAFC', 
                    padding: '1.25rem', 
                    borderRadius: '12px', 
                    border: `1px solid ${isWeakOrWrong ? '#FECACA' : '#E2E8F0'}` 
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '0.75rem' }}>
                    <div style={{ flex: 1 }}>
                      <span style={{ fontSize: '0.75rem', fontWeight: '800', color: '#64748B', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                        Question {idx + 1} ({q.question_type.toUpperCase()})
                      </span>
                      <h4 style={{ margin: '0.2rem 0 0 0', color: '#0F172A', fontSize: '1rem', fontWeight: '700' }}>
                        {q.question_text}
                      </h4>
                    </div>
                    <span 
                      style={{ 
                        padding: '0.35rem 0.8rem', 
                        borderRadius: '9999px', 
                        fontSize: '0.8rem', 
                        fontWeight: '800',
                        background: isWeakOrWrong ? '#DC2626' : '#16A34A',
                        color: '#FFFFFF'
                      }}
                    >
                      {isWeakOrWrong ? `❌ Needs Improvement (${qScore}/100)` : `✅ Strong Answer (${qScore}/100)`}
                    </span>
                  </div>

                  {/* Candidate Answer */}
                  <div style={{ background: '#FFFFFF', padding: '0.85rem 1rem', borderRadius: '8px', border: '1px solid #CBD5E1', marginBottom: '0.75rem' }}>
                    <strong style={{ fontSize: '0.8rem', color: '#475569', display: 'block', marginBottom: '0.25rem' }}>
                      YOUR ANSWER:
                    </strong>
                    <p style={{ margin: 0, fontSize: '0.9rem', color: '#0F172A', whiteSpace: 'pre-wrap' }}>
                      {q.answer ? q.answer.answer_text : 'No answer submitted.'}
                    </p>
                  </div>

                  {/* Feedback & Improvement Notes */}
                  {evalObj && (
                    <div style={{ fontSize: '0.85rem', color: '#334155' }}>
                      {evalObj.missing_concepts && evalObj.missing_concepts.length > 0 && (
                        <div style={{ marginBottom: '0.4rem', color: '#DC2626' }}>
                          <strong>Missing Concepts / Key Gaps: </strong>
                          {Array.isArray(evalObj.missing_concepts) ? evalObj.missing_concepts.join(', ') : evalObj.missing_concepts}
                        </div>
                      )}
                      {evalObj.recommended_follow_up && (
                        <div style={{ color: '#1E3A5F' }}>
                          <strong>💡 How to Improve: </strong>
                          {evalObj.recommended_follow_up}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        ) : (
          <p style={{ color: '#64748B' }}>No questions found for this interview.</p>
        )}
      </div>

      {/* Strengths and Weaknesses */}
      <div className="grid grid-2 gap-6" style={{ marginBottom: '2.5rem' }}>
        <div className="card">
          <h3 style={{ color: '#16A34A', display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
            <CheckCircle size={20} /> STRENGTHS
          </h3>
          <ul style={{ paddingLeft: '1.25rem', fontSize: '0.925rem' }}>
            <li style={{ marginBottom: '0.5rem' }}>Strong technical understanding of core requested framework principles.</li>
            <li style={{ marginBottom: '0.5rem' }}>Clear structured explanation of software architecture and database flow.</li>
            <li style={{ marginBottom: '0.5rem' }}>Good practical examples provided during responses.</li>
          </ul>
        </div>

        <div className="card">
          <h3 style={{ color: '#D97706', display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
            <AlertTriangle size={20} /> AREAS TO IMPROVE
          </h3>
          <ul style={{ paddingLeft: '1.25rem', fontSize: '0.925rem' }}>
            <li style={{ marginBottom: '0.5rem' }}>Elaborate deeper on SQL query optimization and indexing trade-offs.</li>
            <li style={{ marginBottom: '0.5rem' }}>Include microservices scalability and container deployment considerations.</li>
            <li style={{ marginBottom: '0.5rem' }}>Address distributed logging and automated unit testing strategies.</li>
          </ul>
        </div>
      </div>

      {/* Actionable Next Steps Navigation */}
      <div className="card" style={{ textAlign: 'center', background: '#F8FAFC' }}>
        <h3 style={{ marginBottom: '1.25rem' }}>NEXT STEPS FOR CAREER MASTERY</h3>
        <div style={{ display: 'flex', justifyContent: 'center', gap: '1rem', flexWrap: 'wrap' }}>
          <button className="btn btn-primary" onClick={() => onNavigate('roadmap')}>
            <Map size={18} /> View Skill Gaps & 4-Week Roadmap
          </button>
          <button className="btn btn-action" onClick={() => onNavigate('setup')}>
            <PlayCircle size={18} /> Start Another Mock Interview
          </button>
        </div>
      </div>
    </div>
  );
};
